"use strict";
let list = ["Hassan", "Minhaj", "Asif"];
list[2] = "Ahmed";
console.log("I found a bigger dinner table.");
list.push("Kashif", "Saim", "Nasir");
console.log("now:");
console.log("I would like to invite " + list[0] + " for dinner.");
console.log("I would like to invite " + list[1] + " for dinner.");
console.log("I would like to invite " + list[2] + " for dinner.");
console.log("I would like to invite " + list[3] + " for dinner.");
console.log("I would like to invite " + list[4] + " for dinner.");
