"use strict";
let x = 5;
let y = 10;
let z = 5;
console.log("Is x == y? I predict False.");
console.log(x == y);
console.log("Is x != y? I predict True.");
console.log(x != y);
console.log("Is x > y? I predict False.");
console.log(x > y);
console.log("Is x < y? I predict True.");
console.log(x < y);
console.log("Is x >= y? I predict False.");
console.log(x >= y);
console.log("Is x <= y? I predict True.");
console.log(x <= y);
console.log("Is x === y? I predict False.");
console.log(x === y);
console.log("Is x !== y? I predict True.");
console.log(x !== y);
console.log("Is x >= z? I predict True.");
console.log(x >= z);
console.log("Is y <= z? I predict True.");
console.log(y <= z);
